### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by Breitenkamp-DK** [DynamicSadFun/PCFGridActivity#1]
Hi there,

thanks for an awesome pcf control :-)

I am having troubles setting up the control:
Trying to show activities from child customer assets in a subgrid on the parent asset - however I am not sure which fields to apply where.

I keep getting the error:
Could not find a property named '_msdyn_customerassetid_value' on type 'Microsoft.Dynamics.CRM.msdyn_customerasset'.

Thanks in advance.

**Comment by DynamicSadFun** [comment]
@Breitenkamp-DK 
Hello!

What query do you get in the query variable on line 104 of the index.ts file?
What are the contents of tableRecordRow?

Go through your code with a debugger, see what you get back, and depending on the result, edit the fields you need to return.
My code is just a layout. All the magic happens in the query itself, which you actually have to write yourself =)

**Comment by Breitenkamp-DK** [comment]
> @Breitenkamp-DK Hello!
> 
> What query do you get in the query variable on line 104 of the index.ts file? What are the contents of tableRecordRow?
> 
> Go through your code with a debugger, see what you get back, and depending on the result, edit the fields you need to return. My code is just a layout. All the magic happens in the query itself, which you actually have to write yourself =)


> 

Hmmm, where/how do I find that file?

**Comment by Breitenkamp-DK** [comment]
Where/how do I find that file
