### ISSUE TITLE
Can not resolve the segment identifier 'email_engagement.isemailfollowed' in query option.

### ISSUE THREAD

**Issue by rgx91** [DynamicSadFun/PCFGridActivity#2]
Hello,
tried to implement this on a dynamics 365 account form, to get related contact's activity, but getting the following error:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/46424242/236186177-26fdd5a8-0285-4241-8e72-be18d1e512e8.png">
The component settings are the following:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/46424242/236186388-43fd0820-4451-4376-bab1-55b3be70c80b.png">
What can be the problem?
Thank you for your help.

**Comment by DynamicSadFun** [comment]
Hello!
Thank you for trying my PCF. 
It's kind of hard to say exactly what went wrong. It makes sense for you to check the Query variable. What fields are selected through the query and what result is returned, as well as check the data types. Maybe something went wrong with them.
